app/models/visita.py
from app import db

class Visitas(db.Model):
    __tablename__='visita'
    id = db.Column(db.Integer, primary_key=True)
    fecha = db.Column(db.Date, nullable=False)
    motivo = db.Column(db.Text, nullable=False)

    finca_id = db.Column(db.Integer, db.ForeignKey('finca.id'), nullable=False)
    

    
    finca = db.relationship('Fincas',back_populates='visita')

app/routes/home_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify

bp = Blueprint('home', __name__)

@bp.route('/index')
def home():
    return render_template('home/index.html')

app/routes/visita_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.proveedor import Proveedores
from app.models.visita import Visitas
from app.models.finca import Fincas
from app.models.empleado import Empleados
from app import db

bp = Blueprint('visita', __name__)

@bp.route('/visita')
def index():
    data = Visitas.query.all()
    return render_template('visitas/index.html', data=data)

@bp.route('/visita/add', methods=['GET', 'POST'])
def add():

    if request.method == 'POST':
        
        fecha = request.form['fecha']
        motivo = request.form['motivo']
        finca_id = request.form['finca_id']
        
        
        new_visita = Visitas(fecha=fecha,motivo=motivo,finca_id=finca_id)
        db.session.add(new_visita)
        db.session.commit()

        return redirect(url_for('visita.index'))
        
    fincas = Fincas.query.all()
    

    return render_template('visitas/add.html',fincas=fincas)  

@bp.route('/visita/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):

    visita = Visitas.query.get_or_404(id)

    if request.method == 'POST':

        visita.fecha = request.form['fecha']
        visita.motivo = request.form['motivo']
        visita.finca_id = request.form['finca_id']
        
        
        db.session.commit()
        return redirect(url_for('visita.index'))
    
    fincas = Fincas.query.all()
    

    return render_template('visitas/edit.html',visita=visita,fincas=fincas)

    

@bp.route('/visita/delete/<int:id>')
def delete(id):
    
    visita = Visitas.query.get_or_404(id)
    
    db.session.delete(visita)
    db.session.commit()

    return redirect(url_for('visita.index'))

app/templates/visitas/add.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Add</title>
</head>
<style>
    
    .input-group {
  width: 30%; /* Adjust as needed */
  margin: 30px auto;
  padding: 20px;
  border: 1px solid #000000;
  border-radius: 35px;
  background-color: #fffdfd;
}   

.input-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.input-group input[type="text"],
.input-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  box-sizing: border-box; /* Ensures content fits within padding */
}

.input-group button {

    position: center;
    padding:8px 12px;
    margin:8px 0 0;
    font-family:'Montserrat',sans-serif;
    border:2px solid #414150;
    background:0;
    color:#5a5a6e;
    cursor:pointer;
    transition:all .3s  
}

.input-group button:hover {
  background-color: #96a196;
}

h1{
    text-align: center;
   
}
.en-date{
    text-align: left;
    width: 100;
}
.cancelar a{
    color: #5a5a6e;
}
</style>
<body>
    <h1>Agregar Visita</h1>
    <div class="input-group">
    <form action="{{ url_for('visita.add') }}" method="post">
        
        <label for="fecha">Fecha:</label>
        <input type="date" id="fecha" name="fecha" required>
        
        <label for="motivo">Motivo:</label>
        <input type="text" id="Motivo" name="motivo" required>
        
        <label for="finca_id">Finca:</label>
        <select id="finca_id" name="finca_id">
            {% for finca in fincas %}
                <option value="{{ finca.id }}">{{ finca.nombre }}</option>
            {% endfor %}
        </select>
        <button type="submit">Agregar Visita</button>
        <button class="cancelar"><a href="{{ url_for('visita.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/visitas/edit.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    <title>Edit</title>
</head>
<style>
    
    .input-group {
  width: 30%; /* Adjust as needed */
  margin: 30px auto;
  padding: 20px;
  border: 1px solid #000000;
  border-radius: 35px;
  background-color: #fffdfd;
}   

.input-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.input-group input[type="text"],
.input-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  box-sizing: border-box; /* Ensures content fits within padding */
}

.input-group button {

    position: center;
    padding:8px 12px;
    margin:8px 0 0;
    font-family:'Montserrat',sans-serif;
    border:2px solid #414150;
    background:0;
    color:#5a5a6e;
    cursor:pointer;
    transition:all .3s  
}

.input-group button:hover {
  background-color: #96a196;
}

h1{
    text-align: center;
   
}
.en-date{
    text-align: left;
    width: 100;
}
.cancelar a{
    color: #5a5a6e;
}
</style>
<body>
    <h1>Editar Visita</h1>
    <div class="input-group">
    <form action="{{ url_for('visita.edit', id=visita.id) }}" method="post">
        
        <label for="fecha">Fecha:</label>
        <input type="date" id="fecha" name="fecha" value="{{ visita.fecha }}" required>
        
        <label for="motivo">Motivo:</label>
        <input type="text" id="motivo" name="motivo" value="{{ visita.motivo }}" required>
        
        <label for="finca_id">Finca:</label>
        <select id="finca_id" name="finca_id">
            {% for finca in fincas %}
                <option value="{{ finca.id }}">{{ finca.nombre }}</option>
            {% endfor %}
        </select>
        <button type="submit">Actualizar Visita</button>
        <button class="cancelar"><a href="{{ url_for('visita.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/visitas/index.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Visitas</title>
</head>
<body>
    <h1 class="titulo">Lista de Visitas</h1>
    <table class="tablas">
        <tr>
            <th>ID</th>
            <th>Fecha</th>
            <th>Motivo</th>
            <th>Finca</th>
            <th>Acciones</th>
        </tr>   
        {% for visita in data %}
            <tr>
                <td>{{ visita.id }}</td>
                <td>{{ visita.fecha }}</td>
                <td>{{ visita.motivo }}</td>
                <td>{{ visita.finca.nombre }}</td>

             
                
                
                <td>    
                    <a href="{{ url_for('visita.edit', id=visita.id) }}">Editar</a>
                    <a href="{{ url_for('visita.delete', id=visita.id) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}
    </table>
    <div class="botones">
    <a href="{{ url_for('visita.add') }}">Agregar Visitas</a>
    <br>
    <a href="{{ url_for('home.home') }}">Volver al home</a>
    </div>
    
</body>
</html>
{%endblock%}