app/routes/home_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify

bp = Blueprint('home', __name__)

@bp.route('/index')
def home():
    return render_template('home/index.html')

app/routes/proveedor_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.proveedor import Proveedores
from app import db

bp = Blueprint('proveedor', __name__)

@bp.route('/proveedor')
def index():
    data = Proveedores.query.all()
    return render_template('proveedores/index.html', data=data)

@bp.route('/proveedor/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        
        nombre = request.form['nombre']
        contacto = request.form['contacto']
        direccion = request.form['direccion']
        
        new_proveedor = Proveedores(nombre=nombre,contacto=contacto,direccion=direccion)
        db.session.add(new_proveedor)
        db.session.commit()

        return redirect(url_for('proveedor.index'))
        
    

    return render_template('proveedores/add.html')  

@bp.route('/proveedores/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):

    proveedor = Proveedores.query.get_or_404(id)

    if request.method == 'POST':


        proveedor.nombre = request.form['nombre']
        proveedor.contacto = request.form['contacto']
        proveedor.direccion = request.form['direccion']
        

        db.session.commit()
        return redirect(url_for('proveedor.index'))
    

    return render_template('proveedores/edit.html', proveedor=proveedor)
    

@bp.route('/proveedor/delete/<int:id>')
def delete(id):
    
    proveedor = Proveedores.query.get_or_404(id)
    
    db.session.delete(proveedor)
    db.session.commit()

    return redirect(url_for('proveedor.index'))

app/templates/proveedores/add.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Add</title>
</head>
<style>
    
    .input-group {
  width: 30%; /* Adjust as needed */
  margin: 30px auto;
  padding: 20px;
  border: 1px solid #000000;
  border-radius: 35px;
  background-color: #fffdfd;
}   

.input-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.input-group input[type="text"],
.input-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  box-sizing: border-box; /* Ensures content fits within padding */
}

.input-group button {

    position: center;
    padding:8px 12px;
    margin:8px 0 0;
    font-family:'Montserrat',sans-serif;
    border:2px solid #414150;
    background:0;
    color:#5a5a6e;
    cursor:pointer;
    transition:all .3s  
}

.input-group button:hover {
  background-color: #96a196;
}

h1{
    text-align: center;
   
}
.en-date{
    text-align: left;
    width: 100;
}
.cancelar a{
  color: #5a5a6e;
}
</style>
<body>
    <h1>Agregar Proveedor</h1>
    <div class="input-group">
    <form action="{{ url_for('proveedor.add') }}" method="post">

        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required>

        <label for="titulo">Contacto:</label>
        <input type="text" id="contacto" name="contacto" required>

        <label for="titulo">Direccion:</label>
        <input type="text" id="direccion" name="direccion" required>

        <button type="submit">Agregar Proveedor</button>
        <button class="cancelar"><a href="{{ url_for('proveedor.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/proveedores/edit.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Edit</title>
</head>

<body>
    <h1>Editar Proveedor</h1>
    <div class="input-group">
    <form action="{{ url_for('proveedor.edit', id=proveedor.id) }}" method="post">
        
        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ proveedor.nombre }}" required>
        
        <label for="nombre">Contacto:</label>
        <input type="text" id="contacto" name="contacto" value="{{ proveedor.contacto }}" required>
        
        <label for="nombre">Direccion</label>
        <input type="text" id="direccion" name="direccion" value="{{ proveedor.direccion }}" required>
        
        <button type="submit">Actualizar Proveedor</button>
        <button class="cancelar"><a href="{{ url_for('proveedor.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/proveedores/index.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Animal</title>
</head>
<body>
    <h1 class="titulo">Lista de Proveedores</h1>
    <table class="tablas">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Contacto</th>
            <th>Direccion</th>
            <th>Acciones</th>
            
        </tr>
        {% for proveedor in data %}
            <tr>
                <td>{{ proveedor.id }}</td>
                <td>{{ proveedor.nombre }}</td>
                <td>{{ proveedor.contacto }}</td>
                <td>{{ proveedor.direccion }}</td>
                <td>
                    <a href="{{ url_for('proveedor.edit', id=proveedor.id) }}">Editar</a>
                    <a href="{{ url_for('proveedor.delete', id=proveedor.id) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}
    </table>

    <div class="botones">
    <a href="{{ url_for('proveedor.add') }}">Agregar proveedor</a>
    <br>
    
    
    <a href="{{ url_for('home.home') }}">Volver al Home</a>
    <br>
    </div>
   
   
</body>
</html>
{%endblock%}