app/models/mantenimiento.py
from app import db 

class Mantenimientos(db.Model):
    __tablname__='mantenimiento'
    id = db.Column(db.Integer, primary_key=True)
    descripcion = db.Column(db.Text, nullable=False)
    fecha = db.Column(db.Date, nullable=False)

    inventario_id = db.Column(db.Integer, db.ForeignKey('inventario.id'), nullable=False)
    empleado_id = db.Column(db.Integer, db.ForeignKey('empleado.id'), nullable=False)


    empleado = db.relationship('Empleados',back_populates='mantenimiento')
    inventario = db.relationship('Inventarios',back_populates='mantenimiento')

app/routes/home_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify

bp = Blueprint('home', __name__)

@bp.route('/index')
def home():
    return render_template('home/index.html')

app/routes/mantenimiento_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.finca import Fincas
from app.models.mantenimiento import Mantenimientos
from app.models.inventario import Inventarios
from app.models.empleado import Empleados
from app import db

bp = Blueprint('mantenimiento', __name__)

@bp.route('/mantenimiento')
def index():
    data = Mantenimientos.query.all()
    return render_template('mantenimientos/index.html', data=data)

@bp.route('/mantenimiento/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
 
        descripcion = request.form['descripcion']
        fecha = request.form['fecha']
        inventario_id = request.form['inventario_id']
        empleado_id = request.form['empleado_id']

        new_mantenimiento = Mantenimientos(descripcion=descripcion,fecha=fecha,inventario_id=inventario_id,empleado_id=empleado_id)
        db.session.add(new_mantenimiento)
        db.session.commit()
        
        return redirect(url_for('mantenimiento.index'))
    
    inventarios = Inventarios.query.all()
    empleados = Empleados.query.all()

    return render_template('mantenimientos/add.html',inventarios=inventarios,empleados=empleados)  

@bp.route('/mantenimiento/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):

    mantenimiento= Mantenimientos.query.get_or_404(id)

    if request.method == 'POST':

        mantenimiento.descripcion = request.form['descripcion']
        mantenimiento.fecha = request.form['fecha']
        mantenimiento.inventario_id = request.form['inventario_id']
        mantenimiento.empleado_id = request.form['empleado_id']
    
        db.session.commit()
        return redirect(url_for('mantenimiento.index'))
    inventarios = Inventarios.query.all()
    empleados = Empleados.query.all()

    return render_template('mantenimientos/edit.html', mantenimiento=mantenimiento,inventarios=inventarios,empleados=empleados)
    

@bp.route('/mantenimiento/delete/<int:id>')
def delete(id):
    
    mantenimiento = Mantenimientos.query.get_or_404(id)
    
    db.session.delete(mantenimiento)
    db.session.commit()

    return redirect(url_for('mantenimiento.index')  )

app/templates/mantenimientos/add.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Add</title>
</head>
<style>
    
    .input-group {
  width: 30%; /* Adjust as needed */
  margin: 30px auto;
  padding: 20px;
  border: 1px solid #000000;
  border-radius: 35px;
  background-color: #fffdfd;
}   

.input-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.input-group input[type="text"],
.input-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  box-sizing: border-box; /* Ensures content fits within padding */
}

.input-group button {

    position: center;
    padding:8px 12px;
    margin:8px 0 0;
    font-family:'Montserrat',sans-serif;
    border:2px solid #414150;
    background:0;
    color:#5a5a6e;
    cursor:pointer;
    transition:all .3s  
}

.input-group button:hover {
  background-color: #96a196;
}

h1{
    text-align: center;
   
}
.en-date{
    text-align: left;
    width: 100;
}
.cancelar a{
    color: #5a5a6e;
}
</style>
<body>
    <h1>Agregar Mantenimiento</h1>
    <div class="input-group">
    <form action="{{ url_for('mantenimiento.add') }}" method="post">
        <label for="descripcion">Descripcion:</label>
        <input type="text" id="descripcion" name="descripcion" required>

        <label for="fecha">Fecha:</label>
        <input type="date" id="fecha" name="fecha" required>

        <label for="inventario_id">Objeto:</label>
        <select id="inventario_id" name="inventario_id">
            {% for inventario in inventarios %}
                <option value="{{ inventario.id }}">{{ inventario.nombre }}</option>
            {% endfor %}
        </select>
        
         <label for="empleado_id">Empleado:</label>
        <select id="empleado_id" name="empleado_id">
            {% for empleado in empleados %} 
                <option value="{{ empleado.id }}">{{ empleado.nombre }}</option>
            {% endfor %}
        </select>
       
        <button type="submit">Agregar Mantenimiento</button>
        <button class="cancelar"><a href="{{ url_for('mantenimiento.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/mantenimientos/edit.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Edit</title>
</head>

<body>
    <h1>Editar Mantenimiento</h1>
    <div class="input-group">
    <form action="{{ url_for('mantenimiento.edit', id=mantenimiento.id) }}" method="post">

        <label for="descripcion">Descripcion</label>
        <input type="text" id="descripcion" name="descripcion" value="{{ mantenimiento.descripcion}}" required>
        
        <label for="fecha">Fecha:</label>
        <input type="text" id="fecha" name="fecha" value="{{ mantenimiento.fecha}}" required>
        
        <label for="inventario_id">Inventario:</label>
        <select id="inventario_id" name="inventario_id">
            {% for inventario in inventarios %}
                <option value="{{ inventario.id }}">{{ inventario.nombre }}</option>
            {% endfor %}
        </select>

        <label for="empleado_id">Empleado:</label>
        <select id="empleado_id" name="empleado_id">
            {% for empleado in empleados %}
                <option value="{{ empleado.id }}">{{ empleado.nombre }}</option>
            {% endfor %}
        </select>

       
        <button type="submit">Actualizar Mantenimiento</button>
        <button class="cancelar"><a href="{{ url_for('mantenimiento.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/mantenimientos/index.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Movies</title>
</head>
<body>
    <h1 class="titulo">Listado de Mantenimientos</h1>
    <table class="tablas">
        <tr>
            <th>ID</th>
            <th>Descripcion</th>
            <th>Fecha</th>
            <th>Objeto</th>
            <th>Empleado</th>
            <th>Acciones</th>
        </tr>
        {% for mantenimiento in data %}
            <tr>
                <td>{{ mantenimiento.id }}</td>
                <td>{{ mantenimiento.descripcion }}</td>
                <td>{{ mantenimiento.fecha }}</td>
                <td>{{ mantenimiento.inventario.nombre}}</td>
                <td>{{ mantenimiento.empleado.nombre}}</td>
                <td>    
                    <a href="{{ url_for('mantenimiento.edit', id=mantenimiento.id) }}">Editar</a>
                    <a href="{{ url_for('mantenimiento.delete', id=mantenimiento.id) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}
    </table>
    <div class="botones">
    <a href="{{ url_for('mantenimiento.add') }}">Agregar Mantenimiento</a>
    <a href="{{ url_for('home.home') }}">Volver al home</a>
    <br>
    </div>

    
</body>
</html>
{%endblock%}