app/models/finca.py
from app import db

class Fincas(db.Model):
    __tablename__ = 'finca'
    id= db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(100), nullable=False)
    ubicacion = db.Column(db.String(200), nullable=False)
    tamaño = db.Column(db.Float, nullable=False)
    
    empleado = db.relationship('Empleados', back_populates='finca')
    animal = db.relationship('Animales', back_populates='finca')
    inventario = db.relationship('Inventarios', back_populates='finca')
    visita = db.relationship('Visitas', back_populates='finca')

app/routes/finca_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from app.models.finca import Fincas
from app import db

bp = Blueprint('finca', __name__)

@bp.route('/finca')
def index():
    data = Fincas.query.all()
    return render_template('fincas/index.html', data=data)

@bp.route('/finca/add', methods=['GET', 'POST'])
def add():
    if request.method == 'POST':
        
        nombre = request.form['nombre']
        ubicacion = request.form['ubicacion']
        tamaño = request.form['tamaño']
        
        new_animal = Fincas(nombre=nombre,ubicacion=ubicacion,tamaño=tamaño)
        db.session.add(new_animal)
        db.session.commit()
        
        return redirect(url_for('finca.index'))

    return render_template('fincas/add.html')  

@bp.route('/finca/edit/<int:id>', methods=['GET', 'POST'])
def edit(id):

    finca = Fincas.query.get_or_404(id)

    if request.method == 'POST':

        finca.nombre = request.form['nombre']
        finca.ubicacion = request.form['ubicacion']
        finca.tamaño = request.form['tamaño']
        

        db.session.commit()
        return redirect(url_for('finca.index'))

    return render_template('fincas/edit.html', finca=finca)
    

@bp.route('/finca/delete/<int:id>')
def delete(id):
    
    finca = Fincas.query.get_or_404(id)
    
    db.session.delete(finca)
    db.session.commit()

    return redirect(url_for('finca.index'))

app/routes/home_route.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify

bp = Blueprint('home', __name__)

@bp.route('/index')
def home():
    return render_template('home/index.html')

app/templates/fincas/add.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Add</title>
</head>
<style>
    
    .input-group {
  width: 30%; /* Adjust as needed */
  margin: 30px auto;
  padding: 20px;
  border: 1px solid #000000;
  border-radius: 35px;
  background-color: #fffdfd;
}   

.input-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.input-group input[type="text"],
.input-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  box-sizing: border-box; /* Ensures content fits within padding */
}

.input-group button {

    position: center;
    padding:8px 12px;
    margin:8px 0 0;
    font-family:'Montserrat',sans-serif;
    border:2px solid #414150;
    background:0;
    color:#5a5a6e;
    cursor:pointer;
    transition:all .3s
}

.input-group button:hover {
  background-color: #96a196;
}

h1{
    text-align: center;
   
}
.en-date{
    text-align: left;
    width: 100;
}
.cancelar a{
  color: #484848;
}
</style>  
<body>
    <h1>Agregar Finca</h1>
    <div class="input-group">
    <form action="{{ url_for('finca.add') }}" method="post">

        <label for="nombre">Nombre:</label>
        <input type="text" id="nombre" name="nombre" required>

        <label for="ubicacion">Ubicacion:</label>
        <input type="text" id="ubicacion" name="ubicacion" required>

        <label for="tamaño">Tamaño:</label>
        <input type="text" id="tamaño" name="tamaño" required>
    
        <button type="submit">Agregar Finca </button>
        <button class="cancelar"><a href="{{ url_for('finca.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/fincas/edit.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Edit</title>
</head>
<style>
    
    .input-group {
  width: 30%; /* Adjust as needed */
  margin: 30px auto;
  padding: 20px;
  border: 1px solid #000000;
  border-radius: 35px;
  background-color: #fffdfd;
}   

.input-group label {
  display: block;
  margin-bottom: 5px;
  font-weight: bold;
}

.input-group input[type="text"],
.input-group select {
  width: 100%;
  padding: 10px;
  border: 1px solid #ccc;
  border-radius: 3px;
  box-sizing: border-box; /* Ensures content fits within padding */
}

.input-group button {

    position: center;
    padding:8px 12px;
    margin:8px 0 0;
    font-family:'Montserrat',sans-serif;
    border:2px solid #414150;
    background:0;
    color:#5a5a6e;
    cursor:pointer;
    transition:all .3s
}

.input-group button:hover {
  background-color: #96a196;
}

h1{
    text-align: center;
   
}
.en-date{
    text-align: left;
    width: 100;
}
.cancelar a{
  color: #4a4949;
}
</style>
<body>
    <h1>Editar Finca</h1>
    <div class="input-group">
    <form action="{{ url_for('finca.edit', id=finca.id) }}" method="post">

        <label for="">Nombre:</label>
        <input type="text" id="nombre" name="nombre" value="{{ finca.nombre }}" required>

        <label for="">Ubicacion:</label>
        <input type="text" id="nombre" name="ubicacion" value="{{ finca.ubicacion }}" required>

        <label for="">Tamaño:</label>
        <input type="text" id="Tamaño" name="tamaño" value="{{ finca.tamaño }}" required>
        
        <button type="submit">Actualizar Finca</button>
        <button class="cancelar"><a href="{{ url_for('finca.index') }}">Cancelar</a></button>
    </form>
    </div>
</body>
</html>
{%endblock%}

app/templates/fincas/index.html
{% extends"home/index.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Movies</title>
</head> 
<body>
    <h1 class="titulo">Lista de Fincas</h1>
    <table class="tablas">
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Ubicacion</th>
            <th>Tamaño</th>
            <th>Acciones</th>

        {% for fincas in data %}
            <tr>
                <td>{{ fincas.id }}</td>
                <td>{{ fincas.nombre }}</td>
                <td>{{ fincas.ubicacion }}</td>
                <td>{{ fincas.tamaño }}</td>

                <td>    
                    <a href="{{ url_for('finca.edit', id=fincas.id) }}">Editar</a>
                    <a href="{{ url_for('finca.delete', id=fincas.id) }}">Eliminar</a>
                    <!-- Agrega aquí el enlace para eliminar -->
                </td>
            </tr>
        {% endfor %}
    </table>
    <div class="botones">
    <a href="{{ url_for('finca.add') }}">Agregar Finca</a>
    <br>
    <a href="{{ url_for('home.home') }}">Volver al home</a>
    </div>
</body>
</html>
{%endblock%}